name: cash_crop
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  email_validator: ^2.0.1
  file_picker: ^4.6.1
  firebase_app_check: ^0.0.6+14
  firebase_auth: ^3.3.19
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  rive: ^0.9.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
    - assets/images/category food/
    - assets/images/onboarding/
    - assets/animations/
    - assets/icons/
    - assets/images/products/
